---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```


longmera: An R package for calculating means from longitudinal regression models
================


Description
------------

<strong>longmera</strong> is an R package for calculating means from longitudinal generalized linear models. 
As currently implemented, the package uses output from generalized linear mixed-effects models fit using
the **GLMMadaptive** package or generalized estimating equation (GEE) models fit using the **geepack** package to calculate means and their differences based on user-specified
covariate values (contrasts). Standard errors are estimated using the delta method.

Installation
------------

The development version of the package can be installed from GitHub using the **devtools**
package:
```r
devtools::install_github("junedsiddique/longmera")
```

Basic Features
------------

- The package contains a single function named `long_means()` where the only
required arguments are `object`, an object of class MixMod or glmgee and one contrast statement. 

- Up to four contrasts can be specified: two treatment conditions at two time points. 

- Based on the number and type of contrasts specified, the function will also calculate the difference in means for the same condition at two time points, the difference in means
between two conditions at the same time point, and the difference in change between two treatment conditions. 

Basic Use
------------

We illustrate with the gruder data set that is installed with the package. Let `quit` denote an binary outcome, `group` an indicator variable for treatment group,
`time` a continuous covariate for time, `grouptime` the treatment by time interaction, and `id` a unique variable for study participant. A random intercept and slope mixed-effects logistic regression model model is first fit using the glmmAdaptive package
```r
library(GLMMadaptive)
library(longmera)
logit.mix <- mixed_model(fixed = quit ~ group + time + grouptime, 
                   random = ~ time | id, data = gruder,
                   family = binomial())
```

Using the logit.mix object, we can calculate the mean (probability) of `y` for various levels of `tx` and `time

```r
tx.contrast0=c(1, 1, 0, 0) # tx time 0
tx.contrast1=c(1, 1, 4, 4) # tx time 4

ctrl.contrast0=c(1, 0, 0, 0) # ctrl time 0
ctrl.contrast1=c(1, 0, 4, 0) # ctrl time 4


mix.means <- long_means(logit.fit, tx.contrast0=tx.contrast0, tx.contrast1=tx.contrast1,
                   ctrl.contrast0=ctrl.contrast0, ctrl.contrast1=ctrl.contrast1)

mix.means
```

To calculate means using a GEE logistic regression model with the same contrasts, we first fit the model using **geepack**
```r
library(geepack)
logit.gee <- geeglm(quit ~ group + time + grouptime, id=id, 
             data=gruder, corstr="unstructured", family=binomial())
```
And then run the `long_means()` function using the logit.gee object

```r
gee.means <- long_means(logit.gee, tx.contrast0=tx.contrast0, tx.contrast1=tx.contrast1,
                        ctrl.contrast0=ctrl.contrast0, ctrl.contrast1=ctrl.contrast1)

gee.means
```

